apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "minecraft-exporter.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minecraft-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{- .Values.config | toYaml | nindent 4 }}
